### ISSUE TITLE
My app is crashing if i go back to the original route

### ISSUE THREAD

**Issue by shiva2562** [sarbagyastha/youtube_player#21] opened 2019-03-12 11:52 UTC
basically im taking the youtube id from the home route and building a route to another widget to display the youtube video and some data about that video,but when i come back to the original home route the app is crashing,this is what im getting:
The following assertion was thrown while dispatching notifications for VideoPlayerController:
I/flutter ( 7412): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3485 pos 12:
I/flutter ( 7412): '_debugLifecycleState != _ElementLifecycle.defunct': is not true.
I/flutter ( 7412): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 7412): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 7412): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 7412):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 7412): When the exception was thrown, this was the stack:
I/flutter ( 7412): #2      Element.markNeedsBuild 
package:flutter/…/widgets/framework.dart:3485
I/flutter ( 7412): #3      State.setState 
package:flutter/…/widgets/framework.dart:1138
I/flutter ( 7412): #4      _ControlsState.initState.<anonymous closure> 
package:youtube_player/controls.dart:74
I/flutter ( 7412): #5      ChangeNotifier.notifyListeners 
package:flutter/…/foundation/change_notifier.dart:206
I/flutter ( 7412): #6      ValueNotifier.value= 
package:flutter/…/foundation/change_notifier.dart:266
I/flutter ( 7412): #7      VideoPlayerController.setVolume 
package:youtube_player/youtube_player.dart:442
I/flutter ( 7412): <asynchronous suspension>
I/flutter ( 7412): #8      _ControlsState.dispose 
package:youtube_player/controls.dart:97
I/flutter ( 7412): #9      StatefulElement.unmount 
package:flutter/…/widgets/framework.dart:3916
I/flutter ( 7412): #10     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1696
I/flutter ( 7412): #11     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #12     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
I/flutter ( 7412): #13     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #14     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #15     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
I/flutter ( 7412): #16     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #17     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #18     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
I/flutter ( 7412): #19     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #20     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #21     MultiChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4965
I/flutter ( 7412): #22     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #23     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #24     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
I/flutter ( 7412): #25     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #26     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #27     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
I/flutter ( 7412): #28     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #29     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #30     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
I/flutter ( 7412): #31     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #32     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #33     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
I/flutter ( 7412): #34     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #35     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #36     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
I/flutter ( 7412): #37     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #38     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #39     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
I/flutter ( 7412): #40     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #41     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #42     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
I/flutter ( 7412): #43     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #44     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #45     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
I/flutter ( 7412): #46     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #47     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #48     MultiChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4965
I/flutter ( 7412): #49     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #50     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #51     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
I/flutter ( 7412): #52     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #53     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #54     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
I/flutter ( 7412): #55     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #56     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #57     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
I/flutter ( 7412): #58     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #59     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #60     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
I/flutter ( 7412): #61     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #62     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #63     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
I/flutter ( 7412): #64     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #65     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #66     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
I/flutter ( 7412): #67     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #68     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #69     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
I/flutter ( 7412): #70     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #71     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #72     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
I/flutter ( 7412): #73     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #74     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #75     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
I/flutter ( 7412): #76    _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #77     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #78     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
I/flutter ( 7412): #79     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #80     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #81     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
I/flutter ( 7412): #82     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #83     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #84     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
I/flutter ( 7412): #85     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #86     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #87     _SliverPersistentHeaderElement.visitChildren 
package:flutter/…/widgets/sliver_persistent_header.dart:228
I/flutter ( 7412): #88     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #89     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #90     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
I/flutter ( 7412): #91     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #92     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #93     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
I/flutter ( 7412): #94     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #95     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #96     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
I/flutter ( 7412): #97     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #98     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #99     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
I/flutter ( 7412): #100    _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #101    _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #102    SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
I/flutter ( 7412): #103    _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #104    _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #105    ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
I/flutter ( 7412): #106   _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #107    _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #108    MultiChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4965
I/flutter ( 7412): #109    _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #110    _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #111    SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
I/flutter ( 7412): #112    _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #113    _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #114    SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
I/flutter ( 7412): #115    _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #116    _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #117    SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
I/flutter ( 7412): #118    _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/flutter ( 7412): #119    _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1694
I/flutter ( 7412): #120    SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
I/flutter ( 7412): #121    _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1692
I/ExoPlayerImpl( 7412): Release 3027030 [ExoPlayerLib/2.9.6] [land, Redmi 3S, Xiaomi, 23] [goog.exo.core]
Lost connection to device.

**Comment by CaioRolla** [comment] 2019-03-13 02:27
+1
Same error.

**Comment by boloni225** [comment] 2019-03-29 21:09
Same, is there a solution to this?

**Comment by anilkumarmeena** [comment] 2019-04-01 06:32
+1
same error

**Comment by shiva2562** [comment] 2019-04-01 07:48
Actually it is just a break point,i think it works if we run the app through terminal,im not sure tho

**Comment by sarbagyastha** [comment] 2019-04-01 07:55
Sorry for late response folk. I just got time to look out for the issue. The issue is fixed now, newer version in on the way. 😊

**Comment by sarbagyastha** [comment] 2019-04-01 08:22
A new version [**3.2.0**](https://pub.dartlang.org/packages/youtube_player#-changelog-tab-) of the plugin is published, which fixes the issue. Also read the [_Note_](https://pub.dartlang.org/packages/youtube_player#note)

**Closed as completed** 2019-04-07 13:19 UTC
Labels: fixed
